name: Test Go

on:
  pull_request:
    paths:
      - 'go/**'
jobs:
  test_unix:
    name: Go tests ${{ matrix.dolt_fmt }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dolt_fmt: ["", "__DOLT__"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod
          check-latest: true
        id: go
      - name: Test All
        working-directory: ./go
        run: go test ./...
        env:
          DOLT_DEFAULT_BIN_FORMAT: ${{ matrix.dolt_fmt }}
